py36_nose:
  image: python:3.6
  script:
    - apt-get update -q -y
    - pip install -r requirements.txt
    - python -m pytest tests/
    - pylint --rcfile=.pylintrc --output-format=text ethicml/ | tee pylint.txt
    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
    - echo "Pylint score was $score"