image: python:3.6

stages:
  - test
  - lint

before_script:
  - apt-get update -q -y
  - pip install -r requirements.txt

py36:
  stage: test
  script:
    - python -m pytest tests/

pylint:
  stage: lint
  script:
    - pip install pylint
    - python run_pylint.py --disable=fixme --fail-under=8.5
#    - pylint --rcfile=.pylintrc --output-format=text ethicml/ | tee pylint.txt
#    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
#    - echo "Pylint score was $score"