image: python:3.6

stages:
  - test
  - lint

before_script:
  - apt-get update -q -y
  - pip install -r requirements.txt

py36:
  stage: test
  script:
    - python -m pytest tests/

pylint:
  stage: lint
  script:
    - python run_pylint.py