repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--config=.black-config.toml]
      language_version: python3.7
-   repo: https://github.com/asottile/seed-isort-config # statically check for 3rd party libraries and add to isort config
    rev: v2.0.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
    hooks:
    -   id: isort
